In [20]:
import torch
import torch.nn.functional as F
from torch.distributions.categorical import Categorical

In [6]:
mention_logits = torch.tensor([-23.8218, -29.1696, -31.0397, -23.1843, -30.9351,  -5.0278, -23.1951,
        -22.4676, -23.2377, -35.1807, -36.9841, -40.8400, -43.8197, -11.3181,
          0.8319, -14.2533, -22.8118, -10.3641, -40.3568, -23.7730, -42.5738,
        -53.2545, -38.9214, -54.6357, -34.7974, -42.4594, -50.5730, -43.6969,
        -55.2383, -57.1950, -61.1225, -63.7529, -36.4890, -37.1437, -34.6388,
        -36.6400, -19.4003, -62.6985, -47.9273, -49.6853, -40.4932, -36.3148,
        -49.5237, -40.0909, -36.8770, -42.7307, -37.4084, -45.8080, -48.3039,
        -50.9128, -50.9225, -38.7881, -37.0388, -40.3438, -42.3546, -25.9546,
        -63.8379, -48.7609, -50.6291, -59.7314,  -8.1715, -30.6298, -19.7826,
        -26.6724, -28.6843, -24.1925, -31.0684, -34.7105, -34.4987, -36.1484,
        -24.4184, -24.1776, -20.2393, -25.3415, -11.2274, -40.1717, -34.3645,
        -33.9445, -41.6631, -38.1379, -33.4892, -33.5047, -38.9348, -31.7514,
        -38.9079, -44.4178, -45.5116, -44.8648, -34.7051, -33.3338, -31.5459,
        -35.0332, -22.1153, -54.6613, -41.4790, -46.4806, -51.2231, -38.9699,
         19.3175, -27.5975, -28.5766, -24.9072, -34.8822, -39.7073, -40.8001,
        -46.1410, -22.4207, -20.2965, -23.8187, -28.0161, -14.6554, -50.4054,
        -28.2893, -40.2719, -49.7917, -22.4598, -42.7718, -23.3320, -34.3911,
        -29.2988, -35.4139, -38.1391, -40.1606, -42.2020, -29.9000, -28.0076,
        -24.7600, -26.0240, -13.6738, -47.8508, -36.9250, -37.8590, -45.4470,
        -29.9331, -42.0804, -27.4851, -25.5794, -30.7184, -35.6328, -37.8359,
        -41.5550, -19.1359,  -7.8608, -19.2718, -24.8371, -12.4281, -44.5832,
        -30.6081, -37.9282, -44.7456, -24.0381, -37.4551, -15.3704, -21.3703,
        -24.9981, -26.8370, -30.2285,  -8.5167,  -9.2447, -21.6042, -23.3042,
        -11.7980, -37.0005, -21.3596, -31.3394, -37.4550, -14.5930, -32.3305,
        -28.9614, -32.0980, -32.9850, -32.2044, -24.0847, -24.4384, -29.0004,
        -30.3524, -18.6636, -47.1413, -31.3792, -36.4987, -39.3521, -30.1365,
        -39.5029, -30.5340, -35.1382, -33.7575, -27.3095, -26.8057, -30.4607,
        -30.9229, -19.8503, -48.6880, -37.0729, -38.8548, -45.5945, -35.3747,
        -41.4237, -39.0289, -36.2277, -33.0657, -32.3779, -34.0373, -35.7223,
        -24.2855, -54.8596, -42.0205, -43.7190, -49.3890, -39.2617, -46.4547,
        -36.8801, -34.8878, -32.8220, -30.3643, -31.4310, -21.5674, -49.9997,
        -37.7734, -39.7481, -45.1561, -37.5586, -40.6539, -34.9870, -22.2037,
        -21.7070, -23.3714, -14.0350, -43.5364, -33.6363, -37.4227, -40.7665,
        -30.2514, -34.2404, -21.1664, -23.3413, -28.2491, -14.0622, -53.2492,
        -35.5231, -44.2953, -52.6363, -31.4761, -43.5605, -13.0125, -25.5445,
        -10.8753, -52.3350, -37.8763, -41.8542, -52.5220, -32.3843, -47.9423,
        -27.5353, -13.1813, -57.2292, -45.0898, -45.8443, -54.7064, -36.0276,
        -47.5906,   6.6889, -39.7635, -28.6132, -32.4577, -39.6927, -21.3140,
        -33.0223, -44.2625, -37.1600, -40.6274, -49.4090, -29.4156, -45.7630,
         19.8928, -43.8199, -50.4691, -35.9987, -46.5202, -28.4345, -39.8687,
        -30.6905, -35.1582, -31.6575, -10.1713, -21.8439, -28.9179, -33.1647,
        -27.3729,  16.1667, -36.5179, -47.6610, -42.1521, -47.0696, -37.5236,
        -37.6085, -24.9183, -30.8005, -35.3812, -35.6110, -47.2845, -34.7273,
        -46.8581, -46.2719, -45.1246, -50.3178, -44.4910, -45.8026, -31.9133,
        -35.2350, -48.5593, -44.7616, -49.6531, -43.5500, -44.2805, -40.7796,
        -35.7507, -40.6732, -44.5361, -50.9089, -46.7911, -47.9280, -51.3288,
        -46.9962, -50.7340, -48.6498, -52.7662, -42.5085, -48.8337, -44.8562,
        -45.2372, -51.5530, -50.2740, -50.3820, -50.7774, -43.1542, -49.0583,
        -51.2182, -60.6952, -57.1263, -54.6445, -55.8195, -55.6895, -57.6389,
        -53.2292, -61.8634, -53.5261, -56.7226, -35.5421, -46.6197, -42.3172,
        -50.9193, -43.2229, -39.4770, -44.8470, -48.2674, -55.7658, -48.2493,
        -54.1009, -55.7188, -52.6842, -58.1042, -50.7658, -57.8040, -45.9187,
        -55.3737, -43.8225, -45.9851, -46.2028, -49.3932, -38.7652, -43.4288,
        -49.6177, -58.7106, -53.7703, -51.5841, -52.4038, -50.4266, -53.5993,
        -51.5371, -56.2074, -49.8596, -52.7464, -35.1993, -41.7463, -38.6200,
        -35.5786, -37.0659, -42.6759, -48.1532, -42.1196, -47.2134, -48.6208,
        -45.5027, -49.7939, -44.4145, -52.0920, -38.3939, -46.2231, -31.1006,
        -29.2202, -29.7576, -34.2511, -36.8369, -43.6578, -35.6833, -43.8877,
        -43.7076, -42.4711, -44.6260, -40.0684, -44.4719, -32.5368, -37.8491,
         19.8111, -29.4387, -32.9020, -32.0351, -44.6880, -32.9043, -45.9823,
        -46.8492, -43.2647, -47.3606, -43.4894, -43.8037, -28.6937, -37.8392,
        -20.9512, -26.7614, -33.1967, -40.2668, -38.7517, -35.8043, -37.9120,
        -36.9095, -38.8617, -35.6368, -45.1506, -36.9316, -37.5377, -15.6687,
        -22.1364, -28.9729, -26.5123, -35.4699, -38.9066, -37.5694, -41.1701,
        -35.7789, -41.6246, -29.3037, -37.4335,  12.2975, -15.8147,  18.3776,
        -44.7913, -44.8089, -42.3629, -45.9396, -42.2791, -45.0070, -24.2613,
        -39.7015, -35.3186, -25.8633, -53.0339, -53.3910, -49.5295, -54.7160,
        -49.7408, -63.0806, -46.3228, -53.4414, -24.1334, -46.8622, -48.1425,
        -45.3814, -50.9775, -48.6625, -51.7875, -45.5883, -44.7677, -40.3275,
        -46.8325, -46.0980, -50.6097, -44.9555, -53.4102, -38.1783, -50.0275,
        -51.9979, -55.7661, -60.3565, -56.0513, -62.4454, -49.5552, -59.7394,
        -31.0905, -48.3725, -44.6448, -49.8980, -35.2251, -44.3302, -47.3146,
        -46.0892, -57.0358, -43.6360, -50.5498, -35.0456, -45.6044, -40.6097,
        -43.5338, -27.3637,  30.7104, -27.0362, -14.1629, -32.8737, -26.6767,
        -29.7425, -22.8096, -46.7255, -47.2893, -38.9297, -46.4825, -39.9215,
        -42.0039, -41.8684, -37.3068, -35.2897, -44.9843, -32.9954, -46.3169,
        -46.2220, -41.6468, -38.1102, -34.8101,  12.1786,  -9.5466, -12.7633,
        -11.7188, -12.5177,  -1.8030, -29.5942, -32.6373, -27.3432, -23.7059,
        -33.9835, -22.3362, -34.4581, -32.7483, -32.9313, -27.1743, -21.1669,
        -26.2227, -24.0102, -20.6880, -19.0717,   2.8688,  17.3758, -43.8951,
        -44.1632, -37.4657, -28.2420, -48.0607, -26.9203, -49.6965, -44.7290,
        -43.6710, -40.0778, -26.9787, -33.3370, -32.1130, -31.1094, -30.5527,
        -30.1220, -51.1276, -52.7650, -42.1025, -45.0038, -60.3148, -44.6816,
        -54.4761, -53.1708, -49.8174, -43.5202, -49.8534, -54.5352, -36.9109,
        -36.9501, -35.8396, -53.8124, -55.4538, -45.7037, -45.9844, -63.6376,
        -46.6541, -57.3115, -55.0943, -54.2378, -46.4567, -49.7515, -58.4552,
        -40.4690, -31.5209, -56.3436, -57.2910, -48.3780, -47.6883, -62.7556,
        -44.7699, -62.5745, -58.6797, -55.2255, -52.3011, -51.6047, -55.7614,
        -18.4680, -42.9543, -45.3884, -41.1264, -37.5170, -52.6216, -39.0510,
        -51.7767, -47.5055, -46.9494, -42.3609, -36.7778, -42.7192, -35.4319,
        -43.7828, -37.1954, -35.3286, -48.5589, -34.6010, -50.6765, -48.7902,
        -44.2971, -37.9931, -33.9385, -42.4430, -39.4384, -32.7972, -33.1257,
        -44.1019, -34.9626, -51.5244, -51.0113, -49.7910, -41.8202, -39.7196,
        -45.5904, -18.1038, -22.6159, -32.9800, -24.1859, -44.5801, -41.9303,
        -40.0549, -34.4071, -31.8127, -39.1115, -13.4091, -30.8565, -22.6916,
        -45.9467, -43.1395, -42.3568, -35.5730, -30.6039, -36.9807, -28.7932,
        -21.0272, -43.9715, -43.6425, -42.4887, -37.0792, -33.6984, -43.0758,
         20.2183, -44.0755, -41.3378, -41.5366, -36.0453, -25.3455, -35.1962,
        -46.3517, -49.9290, -49.3408, -42.3801, -44.4993, -48.8263, -35.4837,
        -44.4587, -37.7405, -39.4394, -44.3529, -40.3135, -38.5766, -42.1672,
        -46.2543, -25.6782, -30.1661, -33.5003,  15.2523, -15.4996, -16.3206])

In [10]:
topk_indices = torch.squeeze(
    (mention_logits >= 0).nonzero(as_tuple=False), dim=1
)

topk_indices

tensor([ 14,  98, 260, 273, 288, 413, 452, 454, 513, 536, 557, 558, 679, 704])

In [13]:
mention_logits[topk_indices]

tensor([ 0.8319, 19.3175,  6.6889, 19.8928, 16.1667, 19.8111, 12.2975, 18.3776,
        30.7104, 12.1786,  2.8688, 17.3758, 20.2183, 15.2523])

In [17]:
normalized_logits = F.normalize(mention_logits, p=2, dim=0)
normalized_logits

tensor([-0.0224, -0.0274, -0.0291, -0.0218, -0.0290, -0.0047, -0.0218, -0.0211,
        -0.0218, -0.0330, -0.0347, -0.0383, -0.0411, -0.0106,  0.0008, -0.0134,
        -0.0214, -0.0097, -0.0379, -0.0223, -0.0400, -0.0500, -0.0365, -0.0513,
        -0.0327, -0.0399, -0.0475, -0.0410, -0.0518, -0.0537, -0.0574, -0.0598,
        -0.0342, -0.0349, -0.0325, -0.0344, -0.0182, -0.0588, -0.0450, -0.0466,
        -0.0380, -0.0341, -0.0465, -0.0376, -0.0346, -0.0401, -0.0351, -0.0430,
        -0.0453, -0.0478, -0.0478, -0.0364, -0.0348, -0.0379, -0.0398, -0.0244,
        -0.0599, -0.0458, -0.0475, -0.0561, -0.0077, -0.0287, -0.0186, -0.0250,
        -0.0269, -0.0227, -0.0292, -0.0326, -0.0324, -0.0339, -0.0229, -0.0227,
        -0.0190, -0.0238, -0.0105, -0.0377, -0.0323, -0.0319, -0.0391, -0.0358,
        -0.0314, -0.0314, -0.0365, -0.0298, -0.0365, -0.0417, -0.0427, -0.0421,
        -0.0326, -0.0313, -0.0296, -0.0329, -0.0208, -0.0513, -0.0389, -0.0436,
        -0.0481, -0.0366,  0.0181, -0.02

In [18]:
normalized_topk_indices = torch.squeeze(
    (normalized_logits >= 0).nonzero(as_tuple=False), dim=1
)

normalized_topk_indices

tensor([ 14,  98, 260, 273, 288, 413, 452, 454, 513, 536, 557, 558, 679, 704])

In [61]:
cluster = torch.tensor([[0.9, 0.7, 0.6]])

# Reshape the tensor to 1D
cluster = cluster.view(-1)

cluster

tensor([0.9000, 0.7000, 0.6000])

In [104]:
a = torch.tensor([[1,2,3],[4,5,6]])
a.size(-2)

2

In [105]:

print(torch.full_like(a,5))

tensor([[5, 5, 5],
        [5, 5, 5]])


In [102]:
mention_logits1 = torch.cat([torch.Tensor([0]),mention_logits])
mention_dist = Categorical(logits = torch.Tensor([[0,0]]))
print(mention_dist.probs)
print(mention_dist.entropy())

tensor([[0.5000, 0.5000]])
tensor([0.6931])


In [38]:
torch.nn.Parameter(data=torch.Tensor([0]).to("cpu"),
                                        requires_grad=False)

Parameter containing:
tensor([0.])

In [93]:
a = torch.Tensor([[[1,2]]])
print(a.shape)
b = torch.squeeze(a)
print(b.shape)

torch.Size([1, 1, 2])
torch.Size([2])


NameError: name 'Dict' is not defined